import { ArrowUpRight, BriefcaseBusiness, GraduationCap, Handshake, MapPin } from 'lucide-react';
import { SEO } from '../components/SEO';
import { CTAButton, PageHero, SectionHeading } from '../components/ui';
import { contact, editorialImages } from '../data/site';

export default function About(){return <>
  <SEO title="About Ruhan Syed" description="Meet Ruhan Syed, the personal advisor behind Ruhan-Realty and a Realtor Associate at Brown Harris Stevens in Miami Beach."/>
  <PageHero eyebrow="The person behind Ruhan-Realty" title="Business-minded. Hospitality-shaped. Relationship-first." intro="Ruhan Syed is a Realtor Associate with Brown Harris Stevens in Miami Beach, serving clients in English, Hindi and Urdu." image={editorialImages.grove}/>
  <section className="section"><div className="container split"><div><SectionHeading eyebrow="The path to Miami" title="Perspective shaped across cities and industries."/><p className="lead">Ruhan’s story begins in Mumbai, continues through business and technology sales, and moves to the United States—where he earned his MBA in Miami and built hands-on hospitality and front-office experience.</p><p>Those chapters inform an approach grounded in listening, responsiveness, business discipline and calm service. Ruhan-Realty gives that personal approach a digital home, while Brown Harris Stevens provides the established real-estate platform behind it.</p></div><div className="editorial-image-wrap about-image"><img src={editorialImages.interior} width="1600" height="1024" alt="Refined Miami waterfront interior" loading="lazy"/><span className="image-caption">Miami perspective · personal service</span></div></div></section>
  <section className="section dark-section"><div className="container"><SectionHeading eyebrow="Why Ruhan" title="Personal service. Backed by Brown Harris Stevens." intro="A trusted real-estate brand matters. So does having one attentive person who understands your goals."/><div className="area-grid">{[[MapPin,'Miami perspective','Local context shaped by living, studying and building a career in Miami.'],[BriefcaseBusiness,'Business discipline','Clear priorities, thoughtful positioning and responsive follow-through.'],[GraduationCap,'Always informed','An MBA mindset paired with current, verified real-estate information.'],[Handshake,'Relationship first','Hospitality-informed service in English, Hindi and Urdu.']].map(([Icon,h,p])=><article className="stat" key={h}><Icon color="#d8b983"/><h3 style={{fontFamily:'var(--font-display)',fontSize:'1.6rem'}}>{h}</h3><p className="muted">{p}</p></article>)}</div>{contact.bhsProfile&&<a className="btn btn-light" href={contact.bhsProfile} target="_blank" rel="noreferrer" style={{marginTop:'2rem'}}>Official Brown Harris Stevens profile <ArrowUpRight size={15}/></a>}</div></section>
  <section className="section final-cta"><div className="container"><span className="eyebrow">Ruhan-Realty · Brown Harris Stevens</span><h2 className="section-title">Real estate is personal.<br/>The service should be, too.</h2><p className="lead">Start with a direct conversation about what you want your next move to accomplish.</p><CTAButton to="/contact" variant="gold">Start a conversation</CTAButton></div></section>
</>}
