import { CheckCircle2, ExternalLink } from 'lucide-react';
import { ContactLinks, SocialLinks } from '../components/ContactLinks';
import { LeadForm } from '../components/forms/LeadForm';
import { SEO } from '../components/SEO';
import { PageHero, SectionHeading } from '../components/ui';
import { conversionContent, editorialImages } from '../data/site';

const benefits={buy:['Focused property brief','Approved IDX search','Showing coordination'],sell:['Personal—not automated—CMA','Positioning conversation','Clear next-step plan'],rent:['Requirements-led search','Authorized inventory','Responsive follow-up'],landlord:['Property fact collection','Timing and goal review','Listing conversation'],invest:['Objective-first discovery','Financing and timeframe context','No return guarantees'],relocate:['Buy vs. rent context','Area orientation','Brown Harris Stevens referral coordination'],'new-construction':['Authorized current details','Availability confirmation','Direct conversation'],contact:['Personal response','English, Hindi or Urdu','No-pressure conversation']};
const imagery={buy:['beach','interior'],sell:['interior','beach'],rent:['brickell','beach'],landlord:['interior','grove'],invest:['brickell','interior'],relocate:['grove','beach'],'new-construction':['interior','brickell'],contact:['beach','interior']};

export default function ConversionPage({type,relocationLanding=false}){
  const content=conversionContent[type]||conversionContent.contact;
  const [heroKey,secondaryKey]=imagery[type]||imagery.contact;
  const heroImage=editorialImages[heroKey];const secondaryImage=editorialImages[secondaryKey];
  return <>
    <SEO title={content.title} description={content.intro}/>
    <PageHero eyebrow={`Ruhan-Realty · ${content.eyebrow}`} title={relocationLanding?'NY/NJ → Miami: a considered move south.':content.title} intro={content.intro} image={heroImage}/>
    {relocationLanding&&<section className="section-tight"><div className="container"><SectionHeading eyebrow="Relocation planning" title="Move with a plan, not assumptions." intro="Personal guidance from Ruhan Syed, supported by Brown Harris Stevens resources."/><div className="area-grid">{[['Housing options','Compare renting, buying and second-home paths around your timing.'],['Orientation','Understand locations through access, housing types, amenities and daily logistics.'],['Educational resources','Use official property-tax and homestead resources; consult qualified tax/legal professionals.'],['Moving checklist','Organize housing, utilities, transportation, insurance and local logistics.'],['BHS coordination','Explore Brown Harris Stevens referral coordination without implying Ruhan practices outside Florida.'],['Lifestyle fit','Prioritize commute, access and preferences without steering or protected-class claims.']].map(([heading,text])=><article className="card elevated-card" key={heading}><h3 style={{fontFamily:'var(--font-display)',fontSize:'1.4rem'}}>{heading}</h3><p className="muted">{text}</p></article>)}</div><p style={{marginTop:'1.5rem'}}><a href="https://floridarevenue.com/property/Pages/Taxpayers_Exemptions.aspx" target="_blank" rel="noreferrer" className="eyebrow">Florida Department of Revenue education <ExternalLink size={14}/></a></p></div></section>}
    <section className="section"><div className="container"><div className="split" style={{alignItems:'start'}}><div><span className="eyebrow">Ruhan Syed · Brown Harris Stevens</span><h2 className="section-title" style={{margin:'1rem 0'}}>A short brief.<br/><em>A better first conversation.</em></h2><p className="lead">The form adapts to your goal and captures only the useful basics before contact details.</p><div style={{display:'grid',gap:'1rem',marginTop:'2rem'}}>{(benefits[type]||benefits.contact).map(item=><p key={item}><CheckCircle2 size={18} color="#a8814a" style={{display:'inline',marginRight:'.6rem'}}/>{item}</p>)}</div><div className="mini-bhs-card"><small>Affiliated with</small><strong>Brown Harris Stevens</strong><p>Personal attention with the support of a trusted real-estate brand.</p></div>{type==='contact'&&<div className="contact-direct"><h3>Prefer to connect directly?</h3><ContactLinks/><SocialLinks labels/></div>}{type==='contact'?<div className="contact-image-grid"><img src={editorialImages.grove} alt="Miami tropical residential architecture" loading="lazy"/><img src={editorialImages.interior} alt="Miami waterfront residence interior" loading="lazy"/></div>:<div className="conversion-image-strip"><img src={secondaryImage} alt="Miami luxury real-estate editorial" loading="lazy"/></div>}</div><LeadForm intent={type} title={content.formTitle}/></div></div></section>
  </>;
}
