import { ArrowDown, ArrowRight, Building2, Languages, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import heroImage from '../assets/miami-waterfront-hero.png';
import heroAvif from '../assets/miami-waterfront-hero.avif';
import heroWebp from '../assets/miami-waterfront-hero.webp';
import { Assistant } from '../components/Assistant';
import { MarketSnapshot } from '../components/MarketSnapshot';
import { SEO } from '../components/SEO';
import { CTAButton, SectionHeading } from '../components/ui';
import { areas, contact, editorialImages, intents, leadMagnets } from '../data/site';

const schema={ '@context':'https://schema.org','@graph':[
  {'@type':'Person',name:'Ruhan Syed',jobTitle:'Realtor Associate',worksFor:{'@type':'Organization',name:'Brown Harris Stevens'},knowsLanguage:['English','Hindi','Urdu'],url:'https://ruhanrealty.com',telephone:contact.phone,email:contact.email,sameAs:[contact.social.instagram,contact.social.facebook,contact.social.linkedin,contact.bhsProfile].filter(Boolean)},
  {'@type':'WebSite',name:'Ruhan-Realty',alternateName:'Ruhan Syed Miami Real Estate',url:'https://ruhanrealty.com'},
]};

export default function Home(){return <>
  <SEO title="Your Miami Real Estate Connection" description="Ruhan-Realty connects buyers, sellers, renters, investors and relocating clients with Ruhan Syed, Realtor Associate at Brown Harris Stevens." schema={schema}/>
  <section className="hero"><picture><source srcSet={heroAvif} type="image/avif"/><source srcSet={heroWebp} type="image/webp"/><img className="hero-bg" src={heroImage} width="1956" height="804" fetchPriority="high" alt="Contemporary Miami waterfront architecture at sunrise"/></picture><div className="hero-glow"/><div className="container hero-content"><span className="eyebrow" style={{color:'#edcf9d'}}>Ruhan-Realty · Miami, Florida</span><h1 className="display" style={{margin:'1rem 0'}}>Your Miami<br/><em>Real Estate</em> Connection</h1><p className="hero-sub">Buy. Sell. Rent. Relocate.</p><p className="hero-copy">Personal guidance from Ruhan Syed, Realtor Associate, supported by the market knowledge, reach and resources of Brown Harris Stevens.</p><div className="button-row"><CTAButton to="/contact" variant="gold">Talk to Ruhan <ArrowRight size={16}/></CTAButton><CTAButton to="/properties" variant="outline">Search properties</CTAButton></div><div className="hero-identity"><span>Ruhan Syed · Realtor Associate</span><strong>Brown Harris Stevens · Miami Beach</strong><span>English · Hindi · Urdu</span><a href="#intent" aria-label="Continue to options"><ArrowDown size={18}/></a></div></div></section>

  <section className="brokerage-band"><div className="container brokerage-band-inner"><div><small>Personal service, proudly affiliated with</small><strong>BROWN HARRIS STEVENS</strong></div><p>One of America’s most established privately held real-estate firms. Brand references and assets remain subject to approval.</p><Building2 size={34}/></div></section>

  <section id="intent" className="section"><div className="container"><SectionHeading eyebrow="Start with your goal" title="What brings you here?" intro="Choose the path that fits. Every route leads to a focused, useful conversation—not a one-size-fits-all form."/><div className="intent-grid">{intents.map(({label,path,icon:Icon},i)=><Link className="intent-card" key={path} to={path}><span className="intent-number">0{i+1}</span><span className="intent-icon"><Icon size={20}/></span><span><strong>{label}</strong><ArrowRight size={16} style={{float:'right',marginTop:'.4rem'}}/></span></Link>)}</div></div></section>

  <section className="section editorial-section"><div className="container split"><div className="editorial-image-wrap"><img src={editorialImages.interior} width="1600" height="1024" loading="lazy" alt="Warm contemporary Miami waterfront residence interior"/><span className="image-caption">Original editorial imagery · not an MLS listing</span></div><div><span className="eyebrow">A more considered approach</span><h2 className="section-title" style={{margin:'1rem 0'}}>Miami real estate,<br/><em>made personal.</em></h2><p className="lead">Ruhan-Realty is designed around the decisions behind the property: where you want to be, how you want to live, and what a successful move means to you.</p><div className="editorial-points"><p><ShieldCheck/> Clear, objective guidance</p><p><Languages/> Service in English, Hindi and Urdu</p><p><Sparkles/> Brown Harris Stevens resources and reach</p></div><div className="button-row"><CTAButton to="/about">Meet Ruhan</CTAButton><Assistant/></div></div></div></section>

  <section className="section dark-section"><div className="container"><SectionHeading eyebrow="Explore South Florida" title="Find the Miami that fits your next chapter." intro="Editorial area guides paired with objective context and approved live IDX inventory when connected." action={{to:'/areas',label:'All area guides'}}/><div className="area-grid featured-areas">{areas.slice(0,6).map(a=><Link className="area-card" to={`/areas/${a.slug}`} key={a.slug}><img src={a.image} alt={`${a.name} Miami area editorial view`} width="800" height="600" loading="lazy"/><div><span className="eyebrow">Area guide</span><h3>{a.name}</h3><p>{a.summary}</p><span className="area-link">Explore {a.name} <ArrowRight size={15}/></span></div></Link>)}</div></div></section>

  <section className="section market-editorial"><div className="container"><SectionHeading eyebrow="Miami Market Today" title="Context you can verify." intro="Every published statistic includes its source, geography, reporting period and last-updated date. When a feed is unavailable, Ruhan-Realty says so plainly." action={{to:'/market-today',label:'Open market dashboard'}}/><div className="dark-section market-panel"><MarketSnapshot/></div></div></section>

  <section className="section"><div className="container"><div className="split"><div><span className="eyebrow">Ruhan-Realty field notes</span><h2 className="section-title" style={{margin:'1rem 0'}}>Prepare for a better conversation.</h2><p className="lead">Practical resources for serious buyers, sellers, renters, investors and people moving to Miami—with the perspective of Ruhan Syed and Brown Harris Stevens.</p></div><div className="guide-stack">{leadMagnets.map(([label,type],i)=><Link className="guide-card" to={`/${type}?resource=${encodeURIComponent(label)}`} key={label}><span>0{i+1}</span><strong>{label}</strong><ArrowRight size={18}/></Link>)}</div></div></div></section>

  <section className="section final-cta"><div className="container"><span className="eyebrow">Ruhan Syed · Brown Harris Stevens</span><h2 className="section-title">A trusted Miami connection<br/>starts with one conversation.</h2><p className="lead">Tell Ruhan what you’re considering. No pressure—just a thoughtful next step.</p><CTAButton to="/contact" variant="gold">Talk to Ruhan <ArrowRight size={16}/></CTAButton></div></section>
</>}
