import { ArrowDown, ArrowRight, Languages, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import heroImage from '../assets/miami-waterfront-hero.png';
import heroAvif from '../assets/miami-waterfront-hero.avif';
import heroWebp from '../assets/miami-waterfront-hero.webp';
import { Assistant } from '../components/Assistant';
import { MarketSnapshot } from '../components/MarketSnapshot';
import { SEO } from '../components/SEO';
import { CTAButton, SectionHeading } from '../components/ui';
import { areas, intents, leadMagnets } from '../data/site';

const schema = { '@context':'https://schema.org', '@graph':[
  { '@type':'Person', name:'Ruhan Syed', jobTitle:'Realtor Associate', worksFor:{'@type':'Organization',name:'Brown Harris Stevens'}, knowsLanguage:['English','Hindi','Urdu'], url:'https://ruhanrealty.com' },
  { '@type':'WebSite', name:'Ruhan Syed | Miami Real Estate', url:'https://ruhanrealty.com' },
] };

export default function Home(){return <>
  <SEO title="Your Miami Real Estate Connection" description="Buy, sell, rent, invest or relocate in Miami and South Florida with Ruhan Syed, Realtor Associate at Brown Harris Stevens." schema={schema}/>
  <section className="hero"><picture><source srcSet={heroAvif} type="image/avif"/><source srcSet={heroWebp} type="image/webp"/><img className="hero-bg" src={heroImage} width="1956" height="804" fetchPriority="high" alt="Contemporary Miami waterfront architecture at sunrise"/></picture><div className="container hero-content"><span className="eyebrow" style={{color:'#edcf9d'}}>Ruhan Syed · Miami Real Estate</span><h1 className="display" style={{margin:'1rem 0'}}>Your Miami<br/><em>Real Estate</em> Connection</h1><p className="hero-sub">Buy. Sell. Rent. Relocate.</p><p className="hero-copy">Helping clients navigate Miami and South Florida real estate with genuine advice, responsive service and the resources of Brown Harris Stevens.</p><div className="button-row"><CTAButton to="/contact" variant="gold">Talk to Ruhan <ArrowRight size={16}/></CTAButton><CTAButton to="/properties" variant="outline">Search properties</CTAButton></div><div className="hero-identity"><span>Ruhan Syed · Realtor Associate</span><span>Brown Harris Stevens · Miami Beach</span><span>English · Hindi · Urdu</span><a href="#intent" aria-label="Continue to options"><ArrowDown size={18}/></a></div></div></section>
  <section id="intent" className="section"><div className="container"><SectionHeading eyebrow="Start with your goal" title="What brings you here?" intro="Choose the path that fits. Each one opens a focused conversation—no intimidating one-size-fits-all form."/><div className="intent-grid">{intents.map(({label,path,icon:Icon})=><Link className="intent-card" key={path} to={path}><span className="intent-icon"><Icon size={20}/></span><span><strong>{label}</strong><ArrowRight size={16} style={{float:'right',marginTop:'.4rem'}}/></span></Link>)}</div></div></section>
  <section className="section dark-section"><div className="container"><div className="split"><div><span className="eyebrow" style={{color:'#d8b983'}}>The Miami advantage</span><h2 className="section-title" style={{margin:'1rem 0'}}>A personal advisor.<br/><em>Institutional strength.</em></h2><p className="lead">Ruhan brings a relationship-first approach shaped by business, technology sales, hospitality and an MBA earned in Miami—backed by a trusted real-estate brand.</p><div className="button-row"><CTAButton to="/about" variant="light">Meet Ruhan</CTAButton><Assistant/></div></div><div className="card" style={{padding:'2rem',background:'rgba(255,255,255,.06)',borderColor:'rgba(255,255,255,.14)'}}><div style={{display:'grid',gap:'1.5rem'}}><p><ShieldCheck color="#d8b983"/> <strong>Clear, objective guidance</strong><br/><span className="muted">No hype, invented statistics or unsupported claims.</span></p><p><Languages color="#d8b983"/> <strong>Service in English, Hindi & Urdu</strong><br/><span className="muted">Responsive communication that meets clients where they are.</span></p><p><ArrowRight color="#d8b983"/> <strong>Connected follow-through</strong><br/><span className="muted">From first conversation through the details of a transaction.</span></p></div></div></div></div></section>
  <section className="section"><div className="container"><SectionHeading eyebrow="Explore South Florida" title="Find your Miami." intro="Objective, useful area guides with live approved IDX inventory ready to connect when the provider is authorized." action={{to:'/areas',label:'All area guides'}}/><div className="area-grid">{areas.slice(0,6).map((a,i)=><Link className="area-card" to={`/areas/${a.slug}`} key={a.slug} style={{background:`linear-gradient(${125+i*7}deg,#0c1d29,#${i%2?'315f6f':'805d39'})`}}><div><span className="eyebrow" style={{color:'#e5c995'}}>Area guide</span><h3>{a.name}</h3><p>{a.summary}</p></div></Link>)}</div></div></section>
  <section className="section dark-section"><div className="container"><SectionHeading eyebrow="Miami Market Today" title="Context you can verify." intro="Every published statistic includes its source, geography, reporting period and last-updated date. Until approved feeds are connected, the system says so plainly." action={{to:'/market-today',label:'Open market dashboard'}}/><MarketSnapshot/></div></section>
  <section className="section"><div className="container"><div className="split"><div><span className="eyebrow">Practical guides</span><h2 className="section-title" style={{margin:'1rem 0'}}>Prepare for the next conversation.</h2><p className="lead">Useful, admin-managed resources for serious buyers, sellers, renters, investors and people moving to Miami.</p></div><div style={{display:'grid',gap:'.65rem'}}>{leadMagnets.map(([label,type])=><Link className="card" style={{padding:'1rem 1.2rem',display:'flex',justifyContent:'space-between'}} to={`/${type}?resource=${encodeURIComponent(label)}`} key={label}>{label}<ArrowRight size={17}/></Link>)}</div></div></div></section>
  <section className="section dark-section" style={{textAlign:'center'}}><div className="container"><span className="eyebrow" style={{color:'#d8b983'}}>One conversation can clarify a lot</span><h2 className="section-title" style={{maxWidth:800,margin:'1rem auto'}}>What would you like your next Miami move to look like?</h2><p className="lead" style={{margin:'0 auto'}}>Tell Ruhan what you’re considering. No pressure—just a thoughtful next step.</p><CTAButton to="/contact" variant="gold" style={{marginTop:'2rem'}}>Talk to Ruhan <ArrowRight size={16}/></CTAButton></div></section>
</>}
