import { ArrowRight, BadgeCheck, Building2, CheckCircle2, HomeIcon, KeyRound, MapPin, MoveRight, Search, ShieldCheck, Signpost, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import heroImage from '../assets/miami-waterfront-hero.png';
import heroAvif from '../assets/miami-waterfront-hero.avif';
import heroWebp from '../assets/miami-waterfront-hero.webp';
import { AssistantTrigger } from '../components/Assistant';
import { BHSLogo } from '../components/BHSLogo';
import { MarketSnapshot } from '../components/MarketSnapshot';
import { SEO } from '../components/SEO';
import { CTAButton, SectionHeading } from '../components/ui';
import { areas, contact, editorialImages, leadMagnets } from '../data/site';
import { api } from '../services/api';
import { track } from '../services/analytics';

const schema={'@context':'https://schema.org','@graph':[
  {'@type':'Person',name:'Ruhan Syed',jobTitle:'Realtor Associate',worksFor:{'@type':'Organization',name:'Brown Harris Stevens'},knowsLanguage:['English','Hindi','Urdu'],url:'https://ruhanrealty.com',image:'https://ruhanrealty.com/images/ruhan-syed-miami-realtor.webp',telephone:contact.phone,email:contact.email,sameAs:[contact.social.instagram,contact.social.facebook,contact.social.linkedin,contact.bhsProfile].filter(Boolean)},
  {'@type':'WebSite',name:'RuhanRealty.com',alternateName:'Ruhan Syed Miami Real Estate',url:'https://ruhanrealty.com'},
]};

const primaryJourneys=[
  {label:'Buy in Miami',text:'Find the right home with a focused search and clear guidance.',path:'/buy',image:editorialImages.beach,icon:HomeIcon},
  {label:'Sell with confidence',text:'Request a personal CMA and a thoughtful property strategy.',path:'/sell',image:editorialImages.interior,icon:Signpost},
  {label:'Rent in Miami',text:'Share your timing and priorities for a sharper rental search.',path:'/rent',image:editorialImages.brickell,icon:KeyRound},
  {label:'Relocate to Miami',text:'Plan your move with practical local context and personal help.',path:'/ny-nj-to-miami',image:editorialImages.grove,icon:MoveRight},
];

function PropertySearch(){
  const navigate=useNavigate(); const [search,setSearch]=useState({location:'',status:'For Sale',maxPrice:'',beds:''});
  const submit=(event)=>{event.preventDefault();const params=new URLSearchParams(Object.entries(search).filter(([,value])=>value));track('search',{origin:'homepage',...search});navigate(`/properties?${params}`)};
  return <form className="home-search" onSubmit={submit}><div className="home-search-heading"><span className="eyebrow">Live property discovery</span><h2>Search Miami properties</h2><p>Authorized MLS/IDX results appear here when the approved feed is connected.</p></div><div className="home-search-fields"><label><span>Location</span><input value={search.location} onChange={event=>setSearch({...search,location:event.target.value})} placeholder="Brickell, Miami Beach…"/></label><label><span>I want to</span><select value={search.status} onChange={event=>setSearch({...search,status:event.target.value})}><option>For Sale</option><option>For Rent</option></select></label><label><span>Maximum price</span><input inputMode="numeric" value={search.maxPrice} onChange={event=>setSearch({...search,maxPrice:event.target.value})} placeholder="$1,500,000"/></label><label><span>Beds</span><select value={search.beds} onChange={event=>setSearch({...search,beds:event.target.value})}><option value="">Any</option><option value="1">1+</option><option value="2">2+</option><option value="3">3+</option><option value="4">4+</option></select></label><button className="btn btn-gold" type="submit"><Search size={17}/>Search properties</button></div><div className="home-search-links"><span>Popular:</span>{['Brickell','Miami Beach','Coconut Grove','Waterfront'].map(label=><button type="button" key={label} onClick={()=>navigate(`/properties?location=${encodeURIComponent(label)}`)}>{label}</button>)}</div></form>;
}

function RelocationQuickStart(){
  const navigate=useNavigate(); const [data,setData]=useState({origin:'',plan:'',budget:'',timeframe:'',phone:'',email:''});
  const submit=(event)=>{event.preventDefault();sessionStorage.setItem('rr_relocation_handoff',JSON.stringify(data));track('form_step_complete',{intent:'relocate',origin:'homepage'});navigate('/ny-nj-to-miami')};
  const change=event=>setData(current=>({...current,[event.target.name]:event.target.value}));
  return <form className="relocation-quick-form" onSubmit={submit}><span className="eyebrow">Start your move plan</span><h3>NY/NJ → Miami</h3><div className="relocation-fields"><label><span>Moving from</span><input name="origin" value={data.origin} onChange={change} required placeholder="City, state"/></label><label><span>Buy or rent?</span><select name="plan" value={data.plan} onChange={change} required><option value="">Choose one</option><option>Buy</option><option>Rent</option><option>Undecided</option></select></label><label><span>Budget</span><input name="budget" value={data.budget} onChange={change} required placeholder="Your range"/></label><label><span>Timeframe</span><input name="timeframe" value={data.timeframe} onChange={change} required placeholder="e.g. 3–6 months"/></label><label><span>Phone</span><input name="phone" type="tel" value={data.phone} onChange={change} placeholder="Optional"/></label><label><span>Email</span><input name="email" type="email" value={data.email} onChange={change} required placeholder="you@example.com"/></label></div><button className="btn btn-gold" type="submit">Continue my relocation plan <ArrowRight size={16}/></button><small>Next, review your details and choose how Ruhan should respond.</small></form>;
}

function Testimonials(){
  const [items,setItems]=useState([]);
  useEffect(()=>{let active=true;api.content.publicList('TESTIMONIAL').then(data=>{if(active)setItems(data.items||[])}).catch(()=>{});return()=>{active=false}},[]);
  if(!items.length)return <div className="testimonial-empty"><ShieldCheck size={26}/><div><h3>Relationships before transactions.</h3><p>Only authentic, client-approved testimonials are published. New reviews can be managed from the protected content dashboard.</p></div></div>;
  return <div className="testimonial-grid">{items.slice(0,3).map(item=><blockquote key={item._id}><p>“{item.summary||item.body}”</p><footer>{item.title}</footer></blockquote>)}</div>;
}

export default function Home(){return <>
  <SEO title="Your Miami Real Estate Connection" description="Meet Ruhan Syed, Realtor Associate at Brown Harris Stevens, for personal help buying, selling, renting or relocating in Miami and South Florida." schema={schema}/>

  <section className="hero home-hero"><picture><source srcSet={heroAvif} type="image/avif"/><source srcSet={heroWebp} type="image/webp"/><img className="hero-bg" src={heroImage} width="1956" height="804" fetchPriority="high" alt="Contemporary Miami waterfront architecture at sunrise"/></picture><div className="hero-glow"/><div className="container home-hero-grid"><div className="home-hero-copy"><span className="eyebrow">Ruhan Syed · Miami Real Estate</span><h1 className="display">Your Miami<br/><em>Real Estate</em><br/>Connection.</h1><p className="hero-sub">Buy. Sell. Rent. Relocate.</p><p className="hero-copy">Helping you navigate Miami and South Florida real estate with genuine advice, responsive service, and the resources of Brown Harris Stevens.</p><div className="button-row"><CTAButton to="/properties" variant="gold"><Search size={16}/>Search properties</CTAButton><CTAButton to="/contact" variant="outline">Talk to Ruhan <ArrowRight size={16}/></CTAButton></div><div className="hero-trust"><BadgeCheck size={17}/><span>Realtor Associate · Brown Harris Stevens · Miami Beach</span></div></div><aside className="ruhan-hero-card"><div className="ruhan-portrait-frame"><img src={contact.portrait} alt="Ruhan Syed, Realtor Associate at Brown Harris Stevens" width="520" height="680" fetchPriority="high"/></div><div><span>RUHAN SYED</span><strong>Realtor Associate</strong><p>Brown Harris Stevens · Miami Beach</p><small>English · Hindi · Urdu</small></div></aside></div></section>

  <section className="journey-strip" id="intent"><div className="container"><div className="journey-heading"><span className="eyebrow">Begin with your goal</span><h2>What brings you to Miami?</h2></div><div className="journey-grid">{primaryJourneys.map(({label,text,path,image,icon:Icon})=><Link className="journey-card" key={path} to={path}><img src={image} alt="" width="720" height="520" loading="lazy"/><span className="journey-shade"/><span className="journey-icon"><Icon size={19}/></span><div><h3>{label}</h3><p>{text}</p><span>Explore your next step <ArrowRight size={15}/></span></div></Link>)}</div></div></section>

  <section className="search-stage"><div className="container"><PropertySearch/></div></section>

  <section className="section market-home"><div className="container"><SectionHeading eyebrow="Miami Market Today" title="Current context. Clearly sourced." intro="Every published figure includes its source, geography, reporting period and last-updated date. Missing data is shown as unavailable—not invented." action={{to:'/market-today',label:'Explore the market dashboard'}}/><div className="market-home-panel"><MarketSnapshot/></div></div></section>

  <section className="section meet-ruhan"><div className="container meet-ruhan-grid"><div className="meet-portrait"><img src={contact.portrait} alt="Ruhan Syed in Miami" width="620" height="780" loading="lazy"/><span>Personal service · Global perspective</span></div><div><span className="eyebrow">Meet Ruhan</span><h2 className="section-title">A steady guide for<br/><em>an important move.</em></h2><p className="lead">Originally from Mumbai, Ruhan built his career around business, technology sales, hospitality and relationships before earning his MBA in Miami. That experience shapes a calm, responsive real-estate approach centered on listening first.</p><p>Whether you are moving across the city or across the country, Ruhan brings personal attention, practical communication and Brown Harris Stevens resources to every conversation.</p><div className="editorial-points"><p><CheckCircle2/> Clear, objective guidance</p><p><CheckCircle2/> Service in English, Hindi and Urdu</p><p><CheckCircle2/> A relationship beyond the transaction</p></div><div className="button-row"><CTAButton to="/about">Meet Ruhan</CTAButton><AssistantTrigger/></div></div></div></section>

  <section className="section area-showcase"><div className="container"><SectionHeading eyebrow="Explore Miami" title="Different places. Different rhythms." intro="Start with objective context on housing types, access, architecture and notable amenities—then explore approved live listings when IDX is connected." action={{to:'/areas',label:'View all area guides'}}/><div className="area-editorial-grid">{['Brickell','Miami Beach','Coconut Grove','Coral Gables','Sunny Isles','Edgewater'].map(name=>areas.find(area=>area.name===name)).map(area=><Link className="area-editorial-card" to={`/areas/${area.slug}`} key={area.slug}><img src={area.image} alt={`${area.name} area guide`} width="900" height="650" loading="lazy"/><div><span>Area guide</span><h3>{area.name}</h3><p>{area.tags.join(' · ')}</p><strong>Explore {area.name} <ArrowRight size={14}/></strong></div></Link>)}</div></div></section>

  <section className="bhs-credibility"><div className="container bhs-grid"><div><BHSLogo className="bhs-section-logo"/><span className="eyebrow">Personal service. Institutional depth.</span><h2>Personal Service.<br/>Backed by Brown Harris Stevens.</h2><p>Ruhan’s personal guidance is supported by a privately held real-estate platform founded in 1873, with established marketing, technology and market expertise.</p><a className="btn btn-gold" href={contact.bhsProfile} target="_blank" rel="noreferrer">View Ruhan’s official BHS profile <ArrowRight size={16}/></a></div><div className="bhs-facts"><article><strong>1873</strong><span>Brown Harris Stevens founded</span></article><article><Building2/><span>Privately held real-estate platform</span></article><article><Sparkles/><span>Marketing, technology and market resources</span></article><small>BHS references, history, trademarks and visual assets remain subject to broker approval before production launch.</small></div></div></section>

  <section className="section relocation-feature"><div className="container relocation-grid"><div className="relocation-visual"><img src={editorialImages.grove} alt="Tropical South Florida residential setting" width="1000" height="900" loading="lazy"/><div><MapPin/><span>NY / NJ</span><ArrowRight/><span>MIAMI</span></div></div><div><span className="eyebrow">A major life move deserves a plan</span><h2 className="section-title">New York / New Jersey<br/><em>to Miami.</em></h2><p className="lead">Compare buying and renting, orient around Miami’s distinct areas, consider second-home logistics, and coordinate next steps without implying Ruhan practices outside Florida.</p><RelocationQuickStart/></div></div></section>

  <section className="section testimonial-section"><div className="container"><SectionHeading eyebrow="Client experience" title="Trust is earned personally." intro="Ruhan’s work is built around responsive communication, useful guidance and long-term relationships."/><Testimonials/></div></section>

  <section className="section guide-section"><div className="container"><div className="split"><div><span className="eyebrow">Ruhan’s field notes</span><h2 className="section-title">Prepare for a better conversation.</h2><p className="lead">Practical resources for serious buyers, sellers, renters, investors and people moving to Miami.</p></div><div className="guide-stack">{leadMagnets.map(([label,type],i)=><Link className="guide-card" to={`/${type}?resource=${encodeURIComponent(label)}`} key={label}><span>0{i+1}</span><strong>{label}</strong><ArrowRight size={18}/></Link>)}</div></div></div></section>

  <section className="section final-cta"><div className="container"><span className="eyebrow">Ruhan Syed · Brown Harris Stevens</span><h2 className="section-title">A trusted Miami connection<br/>starts with one conversation.</h2><p className="lead">Tell Ruhan what you’re considering. No pressure—just a thoughtful next step.</p><div className="button-row"><CTAButton to="/contact" variant="gold">Talk to Ruhan <ArrowRight size={16}/></CTAButton><AssistantTrigger className="btn btn-outline-light">Ask the website assistant</AssistantTrigger></div></div></section>
</>}
