import { Calendar, MessageCircle, Phone } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { LeadForm } from '../components/forms/LeadForm';
import { SEO } from '../components/SEO';
import { Breadcrumbs, CTAButton, LoadingSkeleton } from '../components/ui';
import { contact } from '../data/site';
import { api } from '../services/api';
import { track } from '../services/analytics';

export default function PropertyDetail(){const {slug}=useParams();const [property,setProperty]=useState();const [error,setError]=useState('');useEffect(()=>{api.properties.one(slug).then(p=>{setProperty(p);track('property_view',{propertyId:p.id})}).catch(e=>setError(e.message))},[slug]);if(error)return <div className="page-hero"><div className="container"><h1 className="section-title">Property not available</h1><p>{error}</p><CTAButton to="/properties" variant="light">Back to search</CTAButton></div></div>;if(!property)return <div className="page-loader"><LoadingSkeleton lines={6}/></div>;const wa=contact.whatsapp?`https://wa.me/${contact.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(`I'm interested in ${property.title}: ${window.location.href}`)}`:'/contact';return <><SEO title={property.title} description={property.description} image={property.image} noindex={!property.indexable} schema={{'@context':'https://schema.org','@type':'Offer',name:property.title,url:window.location.href,price:property.rawPrice,priceCurrency:'USD'}}/><section className="page-hero"><div className="container"><Breadcrumbs items={[{label:'Properties',to:'/properties'},{label:property.title}]}/><h1 className="section-title">{property.title}</h1><p className="lead">{property.location}</p></div></section><section className="section-tight"><div className="container"><div className="split" style={{alignItems:'start'}}><div><div className="property-image" style={{height:'clamp(320px,55vw,620px)',borderRadius:16}}>{property.image&&<img src={property.image} alt={property.imageAlt} width="1200" height="800"/>}</div><p style={{fontSize:'.72rem'}}>{property.attribution}</p><h2 className="section-title" style={{fontSize:'2.8rem',marginTop:'2rem'}}>{property.price}</h2><p>{property.beds} beds · {property.baths} baths · {property.type}</p><p className="lead">{property.description}</p></div><aside className="card" style={{padding:'1.5rem',position:'sticky',top:'110px'}}><h2 style={{fontFamily:'var(--font-display)',fontSize:'1.7rem'}}>Ask Ruhan about this property</h2><div style={{display:'grid',gap:'.6rem'}}><CTAButton to="#inquiry"><Calendar size={16}/>Schedule a showing</CTAButton><a className="btn btn-outline" href={wa}><MessageCircle size={16}/>WhatsApp Ruhan</a><a className="btn btn-outline" href={contact.phone?`tel:${contact.phone}`:'/contact'}><Phone size={16}/>Call Ruhan</a></div></aside></div></div></section><section id="inquiry" className="section" style={{background:'#eee9df'}}><div className="container"><LeadForm intent="buy" title="Ask about this property" property={property}/></div></section></>}
