import { Router } from 'express';
import auth from './authRoutes.js';
import leads from './leadRoutes.js';
import properties from './propertyRoutes.js';
import content from './contentRoutes.js';
import assistant from './assistantRoutes.js';
import { requireAuth } from '../middleware/auth.js';
import { dashboard } from '../controllers/leadController.js';
import { asyncHandler,ok } from '../utils/api.js';
import { databaseReady } from '../config/db.js';
const router=Router();router.get('/health',(_req,res)=>ok(res,{status:'ok',database:databaseReady()?'connected':'degraded',timestamp:new Date().toISOString()}));router.use('/auth',auth);router.use('/leads',leads);router.use('/properties',properties);router.use('/content',content);router.use('/assistant',assistant);router.get('/admin/dashboard',requireAuth,asyncHandler(dashboard));export default router;
