/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { Mail, MessageCircle, Phone } from 'lucide-react';
import { useEffect, useState } from 'react';
import { LoadingSkeleton, Modal } from '../../components/ui';
import { useToast } from '../../context/ToastContext';
import { api } from '../../services/api';

const statuses=['NEW','CONTACTED','QUALIFIED','CONSULTATION','SHOWING','OFFER','CLIENT','CLOSED','NURTURING','LOST'];
export default function AdminLeads(){
  const [filters,setFilters]=useState({search:'',status:'',intent:'',page:1});const [result,setResult]=useState({items:[],pagination:{}});const [selected,setSelected]=useState();const [loading,setLoading]=useState(true);const {notify}=useToast();
  const load=()=>{setLoading(true);api.leads.list(new URLSearchParams(filters)).then(setResult).catch(error=>notify(error.message)).finally(()=>setLoading(false))};
  useEffect(load,[filters.page,filters.status,filters.intent]);
  const update=async(id,status)=>{await api.leads.update(id,{status});notify('Lead status updated');load()};
  return <><div className="admin-top"><div><p className="eyebrow">CRM</p><h1 style={{fontFamily:'var(--font-display)',fontSize:'2.5rem'}}>Lead management</h1></div><b>{result.pagination.total||0} leads</b></div><div className="filters"><input aria-label="Search leads" placeholder="Search name, email, phone" value={filters.search} onChange={event=>setFilters({...filters,search:event.target.value})} onKeyDown={event=>event.key==='Enter'&&load()}/><select aria-label="Filter by status" value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value,page:1})}><option value="">All statuses</option>{statuses.map(status=><option key={status}>{status}</option>)}</select><select aria-label="Filter by intent" value={filters.intent} onChange={event=>setFilters({...filters,intent:event.target.value,page:1})}><option value="">All intents</option>{['BUY','SELL','RENT','LANDLORD','INVEST','RELOCATE','NEW_CONSTRUCTION','CONTACT'].map(intent=><option key={intent}>{intent}</option>)}</select><button className="btn btn-primary" onClick={load}>Search</button></div>{loading?<LoadingSkeleton lines={8}/>:<div className="table-wrap"><table className="admin-table"><thead><tr><th>Lead</th><th>Intent</th><th>Sent via</th><th>Source</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>{result.items.map(lead=><tr key={lead._id}><td><button className="table-link" onClick={()=>setSelected(lead)}>{lead.name}</button><br/><small>{lead.email||lead.phone}</small></td><td>{lead.intent}</td><td><span className="status">{lead.submissionChannel||'WEB'}</span></td><td>{lead.utmSource||lead.referrer||'Direct'}</td><td><select value={lead.status} onChange={event=>update(lead._id,event.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></td><td>{new Date(lead.createdAt).toLocaleDateString()}</td><td><div className="quick-actions">{lead.phone&&<a href={`tel:${lead.phone}`} aria-label="Call"><Phone size={16}/></a>}{lead.email&&<a href={`mailto:${lead.email}`} aria-label="Email"><Mail size={16}/></a>}{lead.phone&&<a href={`https://wa.me/${lead.phone.replace(/\D/g,'')}`} aria-label="WhatsApp"><MessageCircle size={16}/></a>}</div></td></tr>)}</tbody></table></div>}<Modal open={!!selected} onClose={()=>setSelected()} title={selected?.name||'Lead detail'}>{selected&&<div><p><b>{selected.intent}</b> · <span className="status">{selected.status}</span> · sent via <b>{selected.submissionChannel||'WEB'}</b></p><p>{selected.email}<br/>{selected.phone}</p><h3>Requirements</h3><p>{selected.budget} · {selected.location} · {selected.propertyType}<br/>{selected.notes}</p><h3>Attribution</h3><p className="muted">{selected.utmSource||'Direct'} / {selected.utmMedium||'—'} / {selected.utmCampaign||'—'}<br/>Landing: {selected.landingPage}</p><h3>Activity</h3>{selected.activity?.map((activity,index)=><p key={index}><small>{new Date(activity.at).toLocaleString()}</small><br/>{activity.type}: {activity.detail}</p>)}</div>}</Modal></>;
}
