import { ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { areas, contact } from '../data/site';

export function Footer(){return <footer className="footer"><div className="container">
  <div className="footer-brandline"><div><span className="eyebrow">Miami real estate</span><h3>RUHAN-REALTY</h3><p>Ruhan Syed · Realtor Associate</p></div><div className="footer-bhs"><small>Affiliated with</small><strong>BROWN HARRIS STEVENS</strong><span>Miami Beach</span></div></div>
  <div className="footer-grid"><div><p className="footer-intro">A personal Miami real-estate connection, supported by the reach, resources and trusted name of Brown Harris Stevens.</p><p className="muted">English · Hindi · Urdu</p><p className="muted">{contact.office}</p>{contact.bhsProfile&&<a className="eyebrow" href={contact.bhsProfile} target="_blank" rel="noreferrer">Official BHS profile <ArrowUpRight size={14}/></a>}</div><div><h4>Real estate</h4><div className="footer-links"><Link to="/buy">Buy</Link><Link to="/sell">Sell</Link><Link to="/rent">Rent</Link><Link to="/invest">Invest</Link><Link to="/new-construction">New construction</Link></div></div><div><h4>Explore Miami</h4><div className="footer-links">{areas.slice(0,5).map(a=><Link key={a.slug} to={`/areas/${a.slug}`}>{a.name}</Link>)}</div></div><div><h4>Connect</h4><div className="footer-links"><Link to="/contact">Talk to Ruhan</Link>{contact.phone&&<a href={`tel:${contact.phone}`}>{contact.phone}</a>}{contact.email&&<a href={`mailto:${contact.email}`}>{contact.email}</a>}<Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/cookies">Cookie preferences</Link></div></div></div>
  <div className="footer-legal"><p>Equal Housing Opportunity. Fair Housing principles apply. Brown Harris Stevens and MLS/IDX trademarks, attribution and listing disclaimers must be added exactly as approved before launch.</p><p>Information is deemed reliable but is not guaranteed. Market information must display its source, geography, reporting period and last-updated date. Nothing on this site is legal, tax, mortgage, contractual or individualized financial advice. Public launch is conditional on broker, legal and IDX/MLS compliance approval.</p><p>© {new Date().getFullYear()} RuhanRealty.com · RUHAN-REALTY. Personal real-estate marketing website for Ruhan Syed, Realtor Associate with Brown Harris Stevens. Not an independent brokerage.</p></div>
</div></footer>}
