import { ArrowLeft, ArrowRight, Check } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useAttribution } from '../../context/AttributionContext';
import { useToast } from '../../context/ToastContext';
import { api } from '../../services/api';
import { track } from '../../services/analytics';

const goals = {
  buy:['Primary home','Second home','Investment','Not sure yet'], sell:['Sell soon','Understand value','Plan ahead','Other'], rent:['Long-term rental','Seasonal rental','Not sure yet'], landlord:['Find a tenant','Discuss positioning','Future listing'], invest:['Income','Appreciation','Diversification','Not sure yet'], relocate:['Buy','Rent','Undecided'], 'new-construction':['Primary home','Second home','Investment','Just exploring'], contact:['Buying','Selling','Renting','Relocating','Investing','Other'],
};
const propertyTypes=['Condo','Single-family home','Townhome','Multi-family','Land','Other / undecided'];

function Input({label,name,value,onChange,error,type='text',required=false,options,placeholder}) { return <div className="field"><label htmlFor={name}>{label}{required?' *':''}</label>{options?<select id={name} name={name} value={value||''} onChange={onChange} aria-invalid={!!error}><option value="">Select one</option>{options.map(o=><option key={o}>{o}</option>)}</select>:<input id={name} name={name} type={type} value={value||''} onChange={onChange} placeholder={placeholder} aria-invalid={!!error}/>} {error&&<span className="field-error">{error}</span>}</div> }

export function LeadForm({ intent='contact', title='Talk to Ruhan', property }) {
  const { attribution }=useAttribution(); const { notify }=useToast(); const [step,setStep]=useState(0); const [submitting,setSubmitting]=useState(false); const [done,setDone]=useState(false); const [errors,setErrors]=useState({}); const [data,setData]=useState({intent: intent.toUpperCase().replace('-','_'),preferredContact:'PHONE',consent:false,website:''});
  const choices=useMemo(()=>goals[intent]||goals.contact,[intent]);
  const change=(e)=>{const {name,value,type,checked}=e.target;setData(d=>({...d,[name]:type==='checkbox'?checked:value}));setErrors(x=>({...x,[name]:undefined}))};
  const choose=(value)=>{setData(d=>({...d,goal:value}));setErrors({})};
  const validate=()=>{const next={};if(step===0&&!data.goal)next.goal='Choose the option that fits best.';if(step===1){if(!data.budget)next.budget='Please share a range.';if(!data.location)next.location='Add a preferred area or city.';}if(step===2){if(!data.name?.trim())next.name='Name is required.';if(!data.email?.trim()&&!data.phone?.trim())next.email='Add an email or phone number.';if(data.email&&!/^\S+@\S+\.\S+$/.test(data.email))next.email='Enter a valid email.';if(!data.consent)next.consent='Please confirm Ruhan may respond to this request.';}setErrors(next);return !Object.keys(next).length};
  const next=()=>{if(!validate())return;track('form_step_complete',{intent,step:step+1});setStep(s=>s+1)};
  const submit=async(e)=>{e.preventDefault();if(!validate())return;setSubmitting(true);track('form_submit',{intent});try{await api.leads.create({...data,...attribution,landingPage:attribution.landingPage||window.location.href,referrer:attribution.referrer||document.referrer,property:property?{id:property.id,url:window.location.href,title:property.title,address:property.address}:undefined,device:{userAgent:navigator.userAgent,language:navigator.language,viewport:`${innerWidth}x${innerHeight}`}});setDone(true);notify('Thank you. Your request has been sent to Ruhan.')}catch(err){notify(err.message||'We could not send this request. Please try again.')}finally{setSubmitting(false)}};
  if(done)return <div className="form-shell card" role="status" style={{textAlign:'center'}}><div className="intent-icon" style={{margin:'0 auto 1rem'}}><Check/></div><h2 className="section-title" style={{fontSize:'2.3rem'}}>Thank you.</h2><p>Ruhan has received your request and will follow up using your preferred contact method.</p></div>;
  return <form className="form-shell card" onSubmit={submit} onFocus={()=>track('form_start',{intent})}><div className="form-progress" aria-label={`Step ${step+1} of 3`}><span style={{width:`${((step+1)/3)*100}%`}}/></div><p className="eyebrow">Step {step+1} of 3</p><h2 style={{fontFamily:'var(--font-display)',fontSize:'clamp(1.8rem,4vw,2.8rem)',margin:'.6rem 0 1.5rem'}}>{title}</h2><input tabIndex="-1" autoComplete="off" name="website" value={data.website} onChange={change} style={{position:'absolute',left:'-9999px'}} aria-hidden="true"/>
  {step===0&&<fieldset style={{border:0,padding:0}}><legend style={{fontWeight:600,marginBottom:'1rem'}}>What best describes your goal?</legend><div className="choice-grid">{choices.map(c=><button type="button" className={`choice ${data.goal===c?'selected':''}`} aria-pressed={data.goal===c} onClick={()=>choose(c)} key={c}>{c}</button>)}</div>{errors.goal&&<p className="field-error">{errors.goal}</p>}</fieldset>}
  {step===1&&<div className="form-grid"><Input label="Budget or price range" name="budget" value={data.budget} onChange={change} error={errors.budget} required placeholder="e.g. $800k–$1.1m"/><Input label="Preferred location(s)" name="location" value={data.location} onChange={change} error={errors.location} required placeholder="e.g. Brickell, Miami Beach"/><Input label="Property type" name="propertyType" value={data.propertyType} onChange={change} options={propertyTypes}/><Input label="Timeframe / move date" name="moveDate" value={data.moveDate} onChange={change} placeholder="e.g. Within 3 months"/><Input label="Bedrooms" name="beds" value={data.beds} onChange={change} type="number"/><Input label="Financing / preapproval" name="financingStatus" value={data.financingStatus} onChange={change} options={['Cash','Preapproved','Need lender introduction','Not sure / not applicable']}/><div className="field" style={{gridColumn:'1/-1'}}><label htmlFor="notes">What else should Ruhan know?</label><textarea id="notes" name="notes" value={data.notes||''} onChange={change}/></div></div>}
  {step===2&&<div className="form-grid"><Input label="Name" name="name" value={data.name} onChange={change} error={errors.name} required autoComplete="name"/><Input label="Email" name="email" value={data.email} onChange={change} error={errors.email} type="email"/><Input label="Phone" name="phone" value={data.phone} onChange={change} error={errors.phone} type="tel"/><Input label="Preferred contact" name="preferredContact" value={data.preferredContact} onChange={change} options={['PHONE','EMAIL','WHATSAPP','TEXT']}/><label className="consent" style={{gridColumn:'1/-1',display:'flex',gap:'.65rem',alignItems:'start'}}><input type="checkbox" name="consent" checked={data.consent} onChange={change}/> I agree that Ruhan Syed may contact me about this request. Consent is not a condition of purchase. Message/data rates may apply. See the Privacy Policy.</label>{errors.consent&&<span className="field-error" style={{gridColumn:'1/-1'}}>{errors.consent}</span>}</div>}
  <div className="form-actions">{step>0?<button className="btn btn-outline" type="button" onClick={()=>setStep(s=>s-1)}><ArrowLeft size={15}/>Back</button>:<span/>}{step<2?<button className="btn btn-primary" type="button" onClick={next}>Continue<ArrowRight size={15}/></button>:<button className="btn btn-primary" disabled={submitting} type="submit">{submitting?'Sending…':'Send to Ruhan'}<ArrowRight size={15}/></button>}</div></form>;
}
