import { ArrowLeft, ArrowRight, Check, Mail, MessageCircle, Send, ShieldCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useAttribution } from '../../context/AttributionContext';
import { useToast } from '../../context/ToastContext';
import { contact } from '../../data/site';
import { api } from '../../services/api';
import { track } from '../../services/analytics';

const goals={buy:['Primary home','Second home','Investment','Not sure yet'],sell:['Sell soon','Understand value','Plan ahead','Other'],rent:['Long-term rental','Seasonal rental','Not sure yet'],landlord:['Find a tenant','Discuss positioning','Future listing'],invest:['Income','Appreciation','Diversification','Not sure yet'],relocate:['Buy','Rent','Undecided'],'new-construction':['Primary home','Second home','Investment','Just exploring'],contact:['Buying','Selling','Renting','Relocating','Investing','Other']};
const propertyTypes=['Condo','Single-family home','Townhome','Multi-family','Land','Other / undecided'];
const contactOptions=[{value:'PHONE',label:'Phone call'},{value:'EMAIL',label:'Email'},{value:'WHATSAPP',label:'WhatsApp'},{value:'TEXT',label:'Text message'}];

function assistantPrefill(defaultIntent){
  try{
    const handoff=JSON.parse(sessionStorage.getItem('rr_assistant_handoff'));if(!handoff?.profile)return{};
    const profile=handoff.profile;const mappedIntent=(profile.intent==='general'?'contact':profile.intent||defaultIntent).toUpperCase().replace('-','_');
    const budget=profile.minPrice||profile.maxPrice?[profile.minPrice?`$${Number(profile.minPrice).toLocaleString()}`:'',profile.maxPrice?`${profile.minPrice?'– ':'Up to '}$${Number(profile.maxPrice).toLocaleString()}`:''].filter(Boolean).join(''):'';
    return{intent:mappedIntent,budget,location:profile.area||'',propertyType:profile.propertyType||'',beds:profile.beds||'',baths:profile.baths||'',moveDate:profile.timeframe||'',notes:profile.goal?`Assistant context: ${profile.goal}`:''};
  }catch{return{}}
}

function Input({label,name,value,onChange,error,type='text',required=false,options,placeholder}){return <div className="field"><label htmlFor={name}>{label}{required?' *':''}</label>{options?<select id={name} name={name} value={value||''} onChange={onChange} aria-invalid={!!error}><option value="">Select one</option>{options.map(option=>{const item=typeof option==='string'?{value:option,label:option}:option;return <option value={item.value} key={item.value}>{item.label}</option>})}</select>:<input id={name} name={name} type={type} value={value||''} onChange={onChange} placeholder={placeholder} aria-invalid={!!error}/>} {error&&<span className="field-error">{error}</span>}</div>}

export function LeadForm({intent='contact',title='Talk to Ruhan',property}){
  const {attribution}=useAttribution();const {notify}=useToast();const [step,setStep]=useState(0);const [submitting,setSubmitting]=useState('');const [done,setDone]=useState(false);const [sentChannel,setSentChannel]=useState('');const [errors,setErrors]=useState({});const [data,setData]=useState(()=>({intent:intent.toUpperCase().replace('-','_'),preferredContact:'PHONE',consent:false,website:'',...assistantPrefill(intent)}));
  const choices=useMemo(()=>goals[intent]||goals.contact,[intent]);
  const change=e=>{const {name,value,type,checked}=e.target;setData(current=>({...current,[name]:type==='checkbox'?checked:value}));setErrors(current=>({...current,[name]:undefined}))};
  const choose=value=>{setData(current=>({...current,goal:value}));setErrors({})};
  const validate=()=>{const next={};if(step===0&&!data.goal)next.goal='Choose the option that fits best.';if(step===1){if(!data.budget)next.budget='Please share a range.';if(!data.location)next.location='Add a preferred area or city.'}if(step===2){if(!data.name?.trim())next.name='Name is required.';if(!data.email?.trim()&&!data.phone?.trim())next.email='Add an email or phone number.';if(data.email&&!/^\S+@\S+\.\S+$/.test(data.email))next.email='Enter a valid email.';if(!data.consent)next.consent='Please confirm Ruhan may respond to this request.'}setErrors(next);return !Object.keys(next).length};
  const next=()=>{if(!validate())return;track('form_step_complete',{intent,step:step+1});setStep(current=>current+1)};
  const message=()=>[`Hello Ruhan, I’m contacting you through Ruhan-Realty.`,`Name: ${data.name}`,`Interest: ${data.goal||intent}`,`Budget: ${data.budget||'Not specified'}`,`Location: ${data.location||'Not specified'}`,`Property type: ${data.propertyType||'Not specified'}`,`Timeframe: ${data.moveDate||'Not specified'}`,property?`Property: ${property.title} · ${window.location.href}`:'',data.notes?`Notes: ${data.notes}`:''].filter(Boolean).join('\n');
  const payload=channel=>({...data,submissionChannel:channel,...attribution,landingPage:attribution.landingPage||window.location.href,referrer:attribution.referrer||document.referrer,property:property?{id:property.id,url:window.location.href,title:property.title,address:property.address}:undefined,device:{userAgent:navigator.userAgent,language:navigator.language,viewport:`${innerWidth}x${innerHeight}`}});
  const deliver=async(channel,event)=>{event?.preventDefault();if(!validate())return;if(channel==='WHATSAPP'&&!contact.whatsapp){notify('WhatsApp will be available after Ruhan’s approved number is configured.');return}if(channel==='EMAIL'&&!contact.email){notify('Direct email will be available after Ruhan’s approved email is configured.');return}const popup=channel==='WHATSAPP'?window.open('about:blank','_blank'):null;setSubmitting(channel);track('form_submit',{intent,submissionChannel:channel});try{await api.leads.create(payload(channel));setSentChannel(channel);setDone(true);notify('Your inquiry has been saved and sent to Ruhan.');if(channel==='WHATSAPP'&&popup)popup.location.href=`https://wa.me/${contact.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(message())}`;if(channel==='EMAIL')window.location.href=`mailto:${contact.email}?subject=${encodeURIComponent(`Ruhan-Realty ${data.goal||'inquiry'} from ${data.name}`)}&body=${encodeURIComponent(message())}`}catch(err){popup?.close();notify(err.message||'We could not send this request. Please try again.')}finally{setSubmitting('')}};

  if(done)return <div className="form-shell card success-panel" role="status"><div className="intent-icon"><Check/></div><h2 className="section-title">Inquiry received.</h2><p>Your information is safely in the Ruhan-Realty CRM.</p>{sentChannel==='WHATSAPP'&&<p>WhatsApp is opening with your message ready to send.</p>}{sentChannel==='EMAIL'&&<p>Your email app is opening with your message ready to send.</p>}{sentChannel==='WEB'&&<p>Ruhan will follow up using your preferred contact method.</p>}<div className="secure-note"><ShieldCheck size={17}/> Sent securely to Ruhan Syed · Brown Harris Stevens</div></div>;

  return <form className="form-shell card" onSubmit={event=>deliver('WEB',event)} onFocus={()=>track('form_start',{intent})}><div className="form-progress" aria-label={`Step ${step+1} of 3`}><span style={{width:`${((step+1)/3)*100}%`}}/></div><p className="eyebrow">Step {step+1} of 3</p><h2 className="form-title">{title}</h2><input tabIndex="-1" autoComplete="off" name="website" value={data.website} onChange={change} className="honeypot" aria-hidden="true"/>
    {step===0&&<fieldset className="form-fieldset"><legend>What best describes your goal?</legend><div className="choice-grid">{choices.map(choice=><button type="button" className={`choice ${data.goal===choice?'selected':''}`} aria-pressed={data.goal===choice} onClick={()=>choose(choice)} key={choice}>{choice}</button>)}</div>{errors.goal&&<p className="field-error">{errors.goal}</p>}</fieldset>}
    {step===1&&<div className="form-grid"><Input label="Budget or price range" name="budget" value={data.budget} onChange={change} error={errors.budget} required placeholder="e.g. $800k–$1.1m"/><Input label="Preferred location(s)" name="location" value={data.location} onChange={change} error={errors.location} required placeholder="e.g. Brickell, Miami Beach"/><Input label="Property type" name="propertyType" value={data.propertyType} onChange={change} options={propertyTypes}/><Input label="Timeframe / move date" name="moveDate" value={data.moveDate} onChange={change} placeholder="e.g. Within 3 months"/><Input label="Bedrooms" name="beds" value={data.beds} onChange={change} type="number"/><Input label="Financing / preapproval" name="financingStatus" value={data.financingStatus} onChange={change} options={['Cash','Preapproved','Need lender introduction','Not sure / not applicable']}/><div className="field form-wide"><label htmlFor="notes">What else should Ruhan know?</label><textarea id="notes" name="notes" value={data.notes||''} onChange={change}/></div></div>}
    {step===2&&<><div className="form-grid"><Input label="Name" name="name" value={data.name} onChange={change} error={errors.name} required/><Input label="Email" name="email" value={data.email} onChange={change} error={errors.email} type="email"/><Input label="Phone" name="phone" value={data.phone} onChange={change} error={errors.phone} type="tel"/><Input label="How should Ruhan reply?" name="preferredContact" value={data.preferredContact} onChange={change} options={contactOptions}/><label className="consent form-wide"><input type="checkbox" name="consent" checked={data.consent} onChange={change}/> I agree that Ruhan Syed may contact me about this request. Consent is not a condition of purchase. Message/data rates may apply. See the Privacy Policy.</label>{errors.consent&&<span className="field-error form-wide">{errors.consent}</span>}</div><div className="delivery-heading"><span className="eyebrow">Choose how to send</span><h3>Send your inquiry your way.</h3><p>Every option saves your inquiry securely in Ruhan’s CRM first.</p></div><div className="delivery-options"><button className="delivery-card secure" type="submit" disabled={!!submitting}><Send/><span><strong>{submitting==='WEB'?'Sending…':'Send securely'}</strong><small>Fastest · stays on this website</small></span><ArrowRight/></button><button className="delivery-card whatsapp" type="button" disabled={!!submitting||!contact.whatsapp} onClick={event=>deliver('WHATSAPP',event)}><MessageCircle/><span><strong>{submitting==='WHATSAPP'?'Saving…':'Continue on WhatsApp'}</strong><small>{contact.whatsapp?'Opens a ready-to-send message':'Number awaiting configuration'}</small></span><ArrowRight/></button><button className="delivery-card email" type="button" disabled={!!submitting||!contact.email} onClick={event=>deliver('EMAIL',event)}><Mail/><span><strong>{submitting==='EMAIL'?'Saving…':'Continue by email'}</strong><small>{contact.email?'Opens your email app':'Email awaiting configuration'}</small></span><ArrowRight/></button></div></>}
    <div className="form-actions">{step>0?<button className="btn btn-outline" type="button" onClick={()=>setStep(current=>current-1)}><ArrowLeft size={15}/>Back</button>:<span/>}{step<2&&<button className="btn btn-primary" type="button" onClick={next}>Continue<ArrowRight size={15}/></button>}</div>
  </form>;
}
